include $(GOROOT)/src/Make.inc

#TARG=my_new_struct_pkg
#GOFILES=\
	my_new_struct_pkg.go\

# build 하기
#include $(GOROOT)/src/Make.cmd

# package 만들기
#include $(GOROOT)/src/Make.pkg

all: append assert close composite_literals copying_structs_with_unexported_fields deleting_from_maps equality_of_structs_and_arrays function_and_map_equality goroutines_during_init multiple_assignment the_rune_type returns_and_shadowed_variables time error

append:
	$(GC) $@.go && $(LD) -o $@ $@.6
assert:
	$(GC) $@.go && $(LD) -o $@ $@.6
close:
	$(GC) $@.go && $(LD) -o $@ $@.6
composite_literals:
	$(GC) $@.go && $(LD) -o $@ $@.6
copying_structs_with_unexported_fields:
	$(GC) $@.go && $(LD) -o $@ $@.6
deleting_from_maps:
	$(GC) $@.go && $(LD) -o $@ $@.6
equality_of_structs_and_arrays:
	$(GC) $@.go && $(LD) -o $@ $@.6
function_and_map_equality:
	$(GC) $@.go && $(LD) -o $@ $@.6
goroutines_during_init:
	$(GC) $@.go && $(LD) -o $@ $@.6
multiple_assignment:
	$(GC) $@.go && $(LD) -o $@ $@.6
the_rune_type:
	$(GC) $@.go && $(LD) -o $@ $@.6
returns_and_shadowed_variables:
	$(GC) $@.go && $(LD) -o $@ $@.6
time:
	$(GC) $@.go && $(LD) -o $@ $@.6
error:
	$(GC) $@.go && $(LD) -o $@ $@.6

clean:
	rm -f *.6 append assert close composite_literals copying_structs_with_unexported_fields deleting_from_maps equality_of_structs_and_arrays function_and_map_equality goroutines_during_init multiple_assignment the_rune_type returns_and_shadowed_variables time error
