include $(GOROOT)/src/Make.inc

TARG=client
GOFILES=\
	client.go\

# build 하기
include $(GOROOT)/src/Make.cmd

# package 만들기
#include $(GOROOT)/src/Make.pkg

# 이렇게 쓰는 것도 있네..
#GOFMT=gofmt -s -spaces=true -tabindent=false -tabwidth=4
